package com.approvalapplication.application;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Application implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;
	private java.lang.String type;
	private java.lang.Long value;
	private java.lang.String status;
	private com.approvalapplication.application.Employee employee;

	public Application() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.Long getValue() {
		return this.value;
	}

	public void setValue(java.lang.Long value) {
		this.value = value;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public com.approvalapplication.application.Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(
			com.approvalapplication.application.Employee employee) {
		this.employee = employee;
	}

	public Application(java.lang.Long id, java.lang.String type,
			java.lang.Long value, java.lang.String status,
			com.approvalapplication.application.Employee employee) {
		this.id = id;
		this.type = type;
		this.value = value;
		this.status = status;
		this.employee = employee;
	}

}