package com.approvalapplication.application;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Department implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;
	private java.lang.String name;

	private Employee employee;

	public Department() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public com.approvalapplication.application.Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(
			com.approvalapplication.application.Employee employee) {
		this.employee = employee;
	}

	public Department(java.lang.Long id, java.lang.String name,
			com.approvalapplication.application.Employee employee) {
		this.id = id;
		this.name = name;
		this.employee = employee;
	}

}