package com.approvalapplication.application;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Employee implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String id;
	private java.lang.String firstName;
	private java.lang.String lastName;
	private com.approvalapplication.application.Employee manager;
	private com.approvalapplication.application.Department department;

	public Employee() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public com.approvalapplication.application.Employee getManager() {
		return this.manager;
	}

	public void setManager(com.approvalapplication.application.Employee manager) {
		this.manager = manager;
	}

	public com.approvalapplication.application.Department getDepartment() {
		return this.department;
	}

	public void setDepartment(
			com.approvalapplication.application.Department department) {
		this.department = department;
	}

	public Employee(java.lang.String id, java.lang.String firstName,
			java.lang.String lastName,
			com.approvalapplication.application.Employee manager,
			com.approvalapplication.application.Department department) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.manager = manager;
		this.department = department;
	}

}